name: mytsel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  get: 4.6.5
  flutter:
    sdk: flutter
  intl: ^0.17.0
  firebase_core_platform_interface: ^4.8.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  google_sign_in: ^6.1.4
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/elements/
