// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkg0lHN9u9ZVbr35c3PuPfkNAw2kEYUS8',
    appId: '1:636317528702:web:23d4de3238d8e5ce131e2f',
    messagingSenderId: '636317528702',
    projectId: 'recreatemytsel',
    authDomain: 'recreatemytsel.firebaseapp.com',
    storageBucket: 'recreatemytsel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-rpWPaZj4GLCFvq3IDVUXDyAE-umhMjI',
    appId: '1:636317528702:android:65753ef2878739ab131e2f',
    messagingSenderId: '636317528702',
    projectId: 'recreatemytsel',
    storageBucket: 'recreatemytsel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCquddsXSPHMj0shLj4pf-jhrFGW9Y5YGA',
    appId: '1:636317528702:ios:c5a41d90f8f18b20131e2f',
    messagingSenderId: '636317528702',
    projectId: 'recreatemytsel',
    storageBucket: 'recreatemytsel.appspot.com',
    iosClientId: '636317528702-au0chos133e85sse11m4bn83udlq04ef.apps.googleusercontent.com',
    iosBundleId: 'com.mytsel.mytsel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCquddsXSPHMj0shLj4pf-jhrFGW9Y5YGA',
    appId: '1:636317528702:ios:c1a5ee02424ada70131e2f',
    messagingSenderId: '636317528702',
    projectId: 'recreatemytsel',
    storageBucket: 'recreatemytsel.appspot.com',
    iosClientId: '636317528702-ukjrh0upcds4a0hfhqle72v7bs4q6v7d.apps.googleusercontent.com',
    iosBundleId: 'com.mytsel.mytsel.RunnerTests',
  );
}
